numero = int(input(print('Insira um numero para saber sua tabuada : ')))


r0 = (numero * 0)
r1 = (numero * 1)
r2 = (numero * 2)
r3 = (numero * 3)
r4 = (numero * 4)
r5 = (numero * 5)
r6 = (numero * 6)
r7 = (numero * 7)
r8 = (numero * 8)
r9 = (numero * 9)
r10 = (numero * 10)

print('*' * 15)
print('Tabuada do {}'.format(numero))
print('{} x  0 = {}'.format(numero, r0))
print('{} x  1 = {}'.format(numero, r1))
print('{} x  2 = {}'.format(numero, r2))
print('{} x  3 = {}'.format(numero, r3))
print('{} x  4 = {}'.format(numero, r4))
print('{} x  5 = {}'.format(numero, r5))
print('{} x  6 = {}'.format(numero, r6))
print('{} x  7 = {}'.format(numero, r7))
print('{} x  8 = {}'.format(numero, r8))
print('{} x  9 = {}'.format(numero, r9))
print('{} x 10 = {}'.format(numero, r10))
print('*' * 15)
